services:
  - type: web
    name: books-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT services.api.src.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin123
    healthCheckPath: /api/v1/health
    autoDeploy: true
    